# Generated by Django 5.0.6 on 2024-05-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='data_nasc',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
